-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Honeycomb GL"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlaceItem:FireServer(unpack(args))
task.wait(0.5)
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "finish editing component"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
task.wait(0.5)
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Motherboard",
    [2] = game:GetService("Players").LocalPlayer.PcItems:FindFirstChild("A30 C")
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlacePart:FireServer(unpack(args))
task.wait(0.5)
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "groupPart"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
task.wait(0.5)
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "PowerSuply",
    [2] = game:GetService("Players").LocalPlayer.PcItems:FindFirstChild("Silver 1000w")
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlacePart:FireServer(unpack(args))
task.wait(0.5)
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "groupPart"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
task.wait(0.5)
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Cpu",
    [2] = game:GetService("Players").LocalPlayer.PcItems:FindFirstChild("5 1200")
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlacePart:FireServer(unpack(args))
task.wait(0.5)
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "groupPart"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
task.wait(0.5)
for i = 1, 4 do
	-- Script generated by SimpleSpy - credits to exx#9394

	local args = {
		[1] = "Ram",
		[2] = game:GetService("Players").LocalPlayer.PcItems:FindFirstChild("Ram 16Gb")
	}

	game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlacePart:FireServer(unpack(args))
	task.wait(0.5)
	-- Script generated by SimpleSpy - credits to exx#9394

	local args = {
		[1] = "groupPart"
	}

	game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
end
task.wait(0.5)
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Gpu",
    [2] = game:GetService("Players").LocalPlayer.PcItems:FindFirstChild("TR 20")
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlacePart:FireServer(unpack(args))
task.wait(0.5)
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "groupPart"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
task.wait(0.5)
for i = 1, 4 do
	-- Script generated by SimpleSpy - credits to exx#9394

	local args = {
		[1] = "Fan",
		[2] = game:GetService("Players").LocalPlayer.PcItems:FindFirstChild("Stealth 12 RGB")
	}

	game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlacePart:FireServer(unpack(args))
	task.wait(0.5)
	-- Script generated by SimpleSpy - credits to exx#9394

	local args = {
		[1] = "groupPart"
	}

	game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
end
task.wait(0.5)
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Water",
    [2] = game:GetService("Players").LocalPlayer.PcItems:FindFirstChild("LC X2 RGB")
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlacePart:FireServer(unpack(args))
task.wait(0.5)
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "groupPart"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
for i = 1, 2 do
	task.wait(0.5)
	-- Script generated by SimpleSpy - credits to exx#9394

	local args = {
		[1] = "Memory",
		[2] = game:GetService("Players").LocalPlayer.PcItems:FindFirstChild("512Gb")
	}

	game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlacePart:FireServer(unpack(args))
end
task.wait(0.5)
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "groupPart"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))


