-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Honeycomb GL",
    [2] = false,
    [3] = "1"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuyItem:FireServer(unpack(args))
task.wait(0.5)
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "A30 C",
    [2] = false,
    [3] = "1"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuyItem:FireServer(unpack(args))
task.wait(0.5)
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Silver 1000w",
    [2] = false,
    [3] = "1"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuyItem:FireServer(unpack(args))
task.wait(0.5)
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "5 1200",
    [2] = false,
    [3] = "1"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuyItem:FireServer(unpack(args))
for i = 1, 4 do
	task.wait(0.5)
	-- Script generated by SimpleSpy - credits to exx#9394

	local args = {
		[1] = "Ram 16Gb",
		[2] = false,
		[3] = "4"
	}

	game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuyItem:FireServer(unpack(args))
end
for i = 1, 2 do
	task.wait(0.5)
	-- Script generated by SimpleSpy - credits to exx#9394

	local args = {
		[1] = "512Gb",
		[2] = false,
		[3] = "2"
	}

	game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuyItem:FireServer(unpack(args))

end
task.wait(0.5)
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "TR 20",
    [2] = false,
    [3] = "1"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuyItem:FireServer(unpack(args))
for i = 1, 4 do
	task.wait(0.5)
	-- Script generated by SimpleSpy - credits to exx#9394

	local args = {
		[1] = "Stealth 12 RGB",
		[2] = false,
		[3] = "4"
	}

	game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuyItem:FireServer(unpack(args))

end
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "LC X2 RGB",
    [2] = false,
    [3] = "1"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuyItem:FireServer(unpack(args))
